//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Employees = new HashSet<Employee>();
            this.Restaurants = new HashSet<Restaurant>();
            this.DistributeRequests = new HashSet<DistributeRequest>();
        }
    
        public int Id { get; set; }
        public string AreaName { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
        public virtual ICollection<DistributeRequest> DistributeRequests { get; set; }
    }
}
