//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributeRequest
    {
        public DistributeRequest()
        {
            this.DistributeDetails = new HashSet<DistributeDetail>();
        }
    
        public int Id { get; set; }
        public int Status { get; set; }
        public System.DateTime PreserveTill { get; set; }
        public int RestaurantId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int AreaId { get; set; }
    
        public virtual ICollection<DistributeDetail> DistributeDetails { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Area Area { get; set; }
    }
}
