//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.DistributeRequests = new HashSet<DistributeRequest>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Image { get; set; }
        public string Address { get; set; }
        public int AreaId { get; set; }
        public int UserId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<DistributeRequest> DistributeRequests { get; set; }
        public virtual User User { get; set; }
    }
}
