//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BloodBankEntities : DbContext
    {
        public BloodBankEntities()
            : base("name=BloodBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Donor> Donors { get; set; }
        public DbSet<Group> Groups { get; set; }
<<<<<<< HEAD
=======
        public DbSet<Token> Tokens { get; set; }
>>>>>>> 088bfe6b5482766e716d9d1e49288ca88534c0b8
        public DbSet<User> Users { get; set; }
    }
}
