//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
<<<<<<< HEAD
        public string UserName { get; set; }
        public string Password { get; set; }
=======
        public User()
        {
            this.Tokens = new HashSet<Token>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Token> Tokens { get; set; }
>>>>>>> 088bfe6b5482766e716d9d1e49288ca88534c0b8
    }
}
